language: python
pyhton:
- '2.7'
services:
  - postgresql
install: pip install -r requirements.txt
before_script:
  - psql -c 'ALTER USER postgres CREATEDB;'
  - psql -c 'CREATE DATABASE fg_db;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON fg_db TO postgres;' -U postgres
  - python manage.py migrate --noinput
script:
  - python manage.py test
