language: python
pyhton:
- '2.7'
install: pip install -r requirements.txt
script: ./manage.py test
env:
  matrix:
    secure: abA5gtUTF9JjVUdIbYcNB7a1e6KhyXHTT6oScJI4q0A9Zc3qmE+9Ze6dNRmlf97ad5hvJiz9pI/6fRuF5AXzNvmxtSVIA7pXXC76vbLQEdNASEOYWaVdVYT0oN/w2q1uDixqhRfkY4QSCN2s+yjppC+93YNXXSCTcgFf1MBDyGrn4KvTJu44CqcOaFASSrXKcK9rgz/NSerKsPYYEHCwCGenJFXLGwDCDB+Rt0KvtxQ7teL7laSIn3uwEi9w9x9i9n7ojGpQ3G5v3mniBP058UF9hBOI/oyOkK8YkXYzlGX8VceSraY6PwWn9igDu7JylX7kR/7qiyhrOEY0vZ60sqMCmNpgYFB5VU7ea7WJG7cJtLdAPQnwkBNbwu2IcqubqBtbZ3GJoTsOoXQgrw7pb6sZacPsCyK0sqQtfBYEUcIOKML1W7uMHtmKf8vyjh1yp9r7wPMMAcwBYi4BeNZXiatR7Bd/Qe1bvSmBBsTKkcDGEp0bujn/JvRjOZbCjdxv444kKAULI3U/jhs0u/cRMedeUjcQuvJUljNWed2s0/FK4va7IhnqCLdFfTp1vTh8pnVz5Ibra5tJekK7MnRpGPU1A4xVQ0Rr4oKbu51YN4pjI4jixjBhlvuDUMOfjFRgRIHlxPqZgXYpjzANMTIfrh7UhnlQg0CfulPwgz6Mz/U=
