language: python
pyhton:
- '2.7'
services:
  - postgresql
install: pip install -r requirements.txt
before_script:
  - psql -c 'CREATE DATABASE fg_db;' -U postgres
  - python manage.py migrate --noinput
script:
  - python manage.py test
